# Generated by Django 5.1.4 on 2024-12-18 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guest', '0002_appointment_time_time_slot'),
    ]

    operations = [
        migrations.CreateModel(
            name='appointmentbooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone_number', models.BigIntegerField()),
                ('date', models.DateField()),
                ('booking_status', models.CharField(max_length=50)),
                ('selected_slote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slot', to='guest.time_slot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to='guest.userdata')),
            ],
        ),
    ]
